on: [ pull_request ]

jobs:
  migration_job:
    runs-on: ubuntu-latest
    name: CI migration
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Post comment to PR
        uses: peter-evans/create-or-update-comment@v2
        env:
          COMMENT: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [postgres-ai/migration-ci-action][1]

            [1]: https://github.com/marketplace/actions/database-lab-realistic-db-testing-in-ci

            ### Summary        
              | Status | Passed  :heavy_check_mark: |
              |:---:| ---  |
              | Session | #872  |
              | Project | - |
              | DLE instance |  DLE version:v3.1.1-15-g1db723b-20220616-0755 |
              | Data state at | 2022-06-12 00:00:06 +0000 UTC |
              | Duration    | 44s|
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: $COMMENT

      # Run DB migrations with the public action
      - name: DB migrations checker with DLE
        uses: postgres-ai/migration-ci-action@v0.1.1
        id: db-migrations
        with:
          dbname: test_small
          commands: |
            env
            sqitch deploy --verbose
            echo 'Migration has been completed'
          download_artifacts: true
          observation_interval: "10"
          max_lock_duration: "1"
          max_duration: "600"
        env:
          DLMC_CI_ENDPOINT: ${{ secrets.DLMC_CI_ENDPOINT }}
          DLMC_VERIFICATION_TOKEN: ${{ secrets.DLMC_VERIFICATION_TOKEN }}

      # Download artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/*
          if-no-files-found: ignore
        if: always()

      # Show migration summary
      - name: Get the response status
        run: echo "${{ steps.db-migration.outputs.response }}"


